// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactApp1.Server.DTO;

public partial class PostDTO
{
    public int Id { get; set; }

    public string Text { get; set; }

    public DateTime CreatedAt { get; set; }

    public int UserId { get; set; }

}