// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactApp1.Server.DTO;

public partial class UserDTO
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime CreateTime { get; set; }

    public virtual ICollection<PostDTO> Posts { get; set; } = new List<PostDTO>();
}