// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactApp1.Server.Models;

public partial class Post
{
    public int Id { get; set; }

    public string Text { get; set; }

    public DateTime CreateTime { get; set; }

    public int UserId { get; set; }

    public virtual User User { get; set; }
}